# version: '3'
# services:
#   zookeeper:
#     image: confluentinc/cp-zookeeper:5.5.3
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#     volumes:
#       - ./zoo/data:/var/lib/zookeeper/data
#       - ./zoo/log:/var/lib/zookeeper/log
#     networks:
#       - debezium-network
#     restart: always

#   kafka:
#     image: confluentinc/cp-enterprise-kafka:5.5.3
#     depends_on: [zookeeper]
#     environment:
#       KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#       KAFKA_BROKER_ID: 1
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_JMX_PORT: 9991
#     ports:
#       - 9092:9092
#     networks:
#       - debezium-network
#     restart: always

#   kafka-admin:
#     image: 'docker.redpanda.com/redpandadata/console:latest'
#     restart: unless-stopped
#     ports:
#       - 8084:8080
#     environment:
#       - KAFKA_BROKERS=kafka:9092
#     volumes:
#       - ./broker/data:/var/lib/kafka/data
#     depends_on:
#       - zookeeper
#       - kafka
#     networks:
#       - debezium-network

#   debezium:
#     image: debezium/connect
#     environment:
#       BOOTSTRAP_SERVERS: kafka:9092
#       GROUP_ID: 1
#       CONFIG_STORAGE_TOPIC: one-om-dev-connect-configs
#       OFFSET_STORAGE_TOPIC: one-om-dev-connect-offsets
#       STATUS_STORAGE_TOPIC: one-om-dev-connect-status
#     depends_on:
#       - zookeeper
#       - kafka
#     ports:
#       - 8083:8083
#     networks:
#       - debezium-network
#     restart: always

# networks:
#   debezium-network:
#     driver: bridge

services:
  zookeeper:
    platform: linux/x86_64
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
    volumes:
      - ./zoo/data:/var/lib/zookeeper/data
      - ./zoo/log:/var/lib/zookeeper/log
    networks:
      - debezium-network
    restart: always

  kafka:
    platform: linux/x86_64
    image: confluentinc/cp-enterprise-kafka:5.5.3
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2182"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
    ports:
      - 9094:9092
    networks:
      - debezium-network
    restart: always

  kafka-admin:
    platform: linux/x86_64
    image: 'docker.redpanda.com/redpandadata/console:latest'
    restart: unless-stopped
    ports:
      - 8089:8080
    environment:
      - KAFKA_BROKERS=kafka:9092
    volumes:
      - ./broker/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
      - kafka
    networks:
      - debezium-network

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5433:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - debezium-network

  debezium:
    platform: linux/x86_64
    image: debezium/connect
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium-local-connect-configs
      OFFSET_STORAGE_TOPIC: debezium-local-connect-offsets
      STATUS_STORAGE_TOPIC: debezium-local-connect-status
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8088:8083
    networks:
      - debezium-network
    restart: always

networks:
  debezium-network:
    driver: bridge